- backend/app/Enums/UserRole.php
- backend/app/Enums/UserStatus.php
- backend/app/Exceptions/Handler.php
- backend/app/Http/Controllers/Api/V1/AuthController.php
- backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
- backend/app/Http/Resources/V1/UserResource.php
- backend/app/Models/User.php
- backend/composer.json
- backend/composer.lock
- backend/config/services.php
- backend/database/factories/UserFactory.php
- backend/database/migrations/2024_03_04_093021_update_user_table.php
- backend/database/migrations/2024_03_05_032159_make_password_nullable.php
- backend/database/migrations/2024_03_05_033615_add_provider_to_users_table.php
- backend/database/seeders/DatabaseSeeder.php
- backend/database/seeders/UserSeeder.php
- backend/routes/api.php
- Update user table
- Implemented login and logout endpoints.
- Implemented login with Google endpoint.
User would be able to login to the application using their email or Google account in order to access protected resources.
[SBNB-42 Backend - Create API to login user and implement OAuth](https://framgiaph.backlog.com/view/SBNB-42)
- New Migrations
- run `php artisan migrate` to apply new migrations
- Google API Client
- run `composer install` to apply new dependency
- create a new project in the Google Cloud Console, enable the Google+ API, and obtain the client ID and client secret
- add the corresponding `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` values to your `.env` file
N/A
> [FEATURE] SBNB-42 Backend - Create API to login user and implement OAuth

- .github/workflows/development.yml
- Reverted the accidental push
- Added master as branch for workflows
- To revert the changes made by an accidental push and to make the workflow run
Why are these changes necessary?
- To revert the changes made by an accidental push and to make the workflow run
N/A
> added workflow and reset the master branch

- .github/workflows/development.yml
- added master to the branch list for triggering the github workflow
- to have an automated checker for pull requests to the master branch
Why are these changes necessary?
- to make it easier for developers to see the possible errors and problems before merging the pull request to the master branch
SBNB-1
N/A
N/A
> updated the workflows to work on master branch

- frontend/src/app/(auth)/login/page.tsx
- frontend/src/app/(auth)/signup/page.tsx
- frontend/src/app/(shared)/profile/EmailField.tsx
- frontend/src/app/(shared)/profile/LegalNameField.tsx
- frontend/src/app/(shared)/profile/PasswordField.tsx
- frontend/src/app/(shared)/profile/ProfileComponent.tsx
- frontend/src/app/(shared)/profile/page.tsx
- frontend/src/app/components/ApprovalModal.tsx
- frontend/src/app/interfaces/ProfileFieldProps.ts
- Created user account management page and components
- Adjusted padding of pages
- Modified ApprovalModal to use ModalProps interface
- Implement user account management markup
- Slack Link:https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1709862984118889
- Task Link: https://framgiaph.backlog.com/view/SBNB-51
Include screenshots to visually demonstrate the changes made by this pull request.
_User account management screen_
N/A
N/A
> Added User account management page and components

- frontend/.prettierrc
- changed prettier tab width
To set prettier standards to code
- Slack Link: 
- Task Link: https://framgiaph.backlog.com/view/SBNB-1
N/A
N/A
N/A
> Update - Changed Prettier Format

- frontend/src/app/(guest)/accommodations/new/page.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
- frontend/src/app/(host)/listings/accommodations/edit/page.tsx
- frontend/src/app/(host)/listings/accommodations/new/page.tsx
- frontend/src/app/(host)/listings/experiences/[id]/page.tsx
- frontend/src/app/(host)/listings/experiences/edit/page.tsx
- frontend/src/app/(host)/listings/experiences/new/page.tsx
- frontend/src/app/components/navbar/NavbarDropdown.tsx
- Move `host/new-listing` to `(host)/listings/accommodations/new`
For more readable and informative routes
[Slack Link]()
[Ticket Link](https://framgiaph.backlog.com/view/SBNB-59)
N/A
N/A
> fix page routing

- backend/app/Http/Resources/V1/AdminResource.php
- backend/app/Http/Resources/V1/UserResource.php
- change pascal to snake case
For uniform naming of variables
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1710209904095069
- Task Link: https://framgiaph.backlog.com/view/SBNB-42
Before
After
N/A
N/A
> change pascal to snake case

- backend/app/Http/Controllers/Api/V1/UserController.php
- backend/app/Http/Requests/V1/PasswordUpdateRequest.php
- backend/app/Http/Requests/V1/UserUpdateRequest.php
- backend/app/Models/User.php
- backend/routes/api.php
Created a separate API for updating the user password.
Enhance app functionality and the integration process of user management.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1710320946110699)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-52)
N/A
N/A
> Backend - Separate password update

- backend/app/Exceptions/Handler.php
- backend/app/Http/Controllers/Api/V1/AdminAuthController.php
- backend/app/Http/Controllers/Api/V1/AuthController.php
- backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
- backend/app/Http/Requests/V1/GoogleLoginRequest.php
- backend/app/Http/Requests/V1/GoogleRegistrationRequest.php
- backend/app/Models/Admin.php
- backend/app/Models/User.php
- backend/routes/api.php
- Move business logic to model
- Update google login endpoint to accept user role
- Separation of concern and controller would only handle responses
- Set user role upon first google login
- Slack Link:
- Task Link: https://framgiaph.backlog.com/view/SBNB-39
N/A
N/A
> update google login endpoint

- frontend/src/app/(auth)/login/LoginForm.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
- frontend/src/app/api/auth/[...nextauth]/nextAuthOptions.ts
- frontend/src/app/utils/helpers/accommodation/request.ts
- frontend/src/app/utils/helpers/userHelper.ts
Deleted the unnecessary console logs.
To improve security and reduce code complexity.
- Slack Link: https://framgiaph.backlog.com/view/SBNB-43
- Task Link:
N/A
N/A
N/A
> Removed unnecessary console logs.

- backend/app/Http/Controllers/Api/V1/AccommodationController.php
- backend/app/Models/Accommodation.php
- backend/app/Models/Listing.php
- backend/app/Models/Media.php
- Transferred some logic to the respective models
- Make reusable functions
- Clean code
To adhere to best practices and enhance the maintainability, readability, and reusability of the accommodation management (BE).
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1710816146165409)
- Task Links: [SBNB-57](https://framgiaph.backlog.com/view/SBNB-57) [SBNB-63](https://framgiaph.backlog.com/view/SBNB-63)
N/A
N/A
> Backend - Refactored and clean code for Accommodation Management

- frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
- frontend/src/app/(host)/listings/experiences/edit/EditExperienceForm.tsx
- frontend/src/app/(host)/listings/experiences/edit/page.tsx
- frontend/src/app/(host)/listings/experiences/new/NewExperienceForm.tsx
- frontend/src/app/(host)/listings/experiences/new/page.tsx
- frontend/src/app/components/DeleteModal.tsx
- frontend/src/app/components/experiences/ExperienceApprovalModal.tsx
- frontend/src/app/components/experiences/InclusionsListbox.tsx
- frontend/src/app/components/experiences/LanguagesListbox.tsx
- frontend/src/app/components/experiences/Slider.tsx
- frontend/src/app/utils/enums.ts
- Created NewExperienceForm
- Created EditListingForm
- Updated previous code (accommodations forms) since the delete and cancel buttons were not working as intended.
As a host, I want to list an experience or adventure by providing details about the activity to attract interested guests.
- Slack Link: 
- Task Link: https://framgiaph.backlog.com/view/SBNB-80
NewExperienceForm:
EditExperienceForm:
N/A
Upload photo section will be added during integration
> Markup - Create components and pages for experiences (Create, Update, Delete)

- backend/app/Http/Controllers/Api/V1/AuthController.php
- backend/app/Http/Controllers/Api/V1/BookingController.php
- backend/app/Http/Controllers/Api/V1/CalendarController.php
- backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
- backend/app/Http/Requests/V1/BookingRequest.php
- backend/app/Models/Booking.php
- backend/app/Models/Calendar.php
- backend/app/Models/Listing.php
- backend/app/Models/User.php
- backend/app/Rules/DateAvailabilityRule.php
- backend/app/Rules/MinMaxDaysRule.php
- backend/app/Rules/MinMaxGuestsRule.php
- backend/database/migrations/2024_03_20_062759_add_booking_id_to_calendars.php
- backend/routes/api.php
- Added booking foreign key to calendar.
- Created booking endpoint.
- Add booking request and validations.
- Add middleware to booking.
- Host would know is someone has already reserved the dates.
- Guest would be able to book accommodations and experiences.
- Ensure request inputs are valid.
- Only guest users can book an accommodation or experience.
- Slack Link:
- Task Link: 
- https://framgiaph.backlog.com/view/SBNB-75
- https://framgiaph.backlog.com/view/SBNB-84
- New migration file is added please run `php artisan migrate`
- There is only one endpoint for booking accommodations and experiences.
> add booking accommodation and experience endpoint

- frontend/src/app/components/calendar/ListingsDropdown.tsx
- frontend/src/app/utils/helpers/accommodation/request.ts
- frontend/src/app/utils/helpers/availability/requests.ts
- Update API endpoints in clients for accommodations and listing availability
- API was updated so we need to update the calls in the client.
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1711002267072009
- Task Link: https://framgiaph.backlog.com/view/SBNB-92
N/A
N/A
> update listings api calls

- frontend/src/app/(guest)/history/page.tsx
- frontend/src/app/components/BookingHistory.tsx
- frontend/src/app/components/BookingStatus.tsx
- Created markup for booking history
As a guest, I want to manage my bookings, including viewing past and upcoming stays, to keep track of my travel plans.
- Slack Link: https://framgiaph.backlog.com/view/SBNB-77
- Task Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1711072511553879
N/A
N/A
> Markup - Create components and pages for managing bookings and bookings history

- backend/app/Http/Controllers/Api/V1/BookingController.php
- backend/app/Http/Controllers/Api/V1/ListingController.php
- backend/app/Http/Middleware/CheckOwnership.php
- backend/app/Models/Booking.php
- backend/app/Models/Calendar.php
- backend/app/Models/Listing.php
- backend/app/Models/User.php
- backend/routes/api.php
- Added APIs for delete, cancel, and show bookings by user.
- Updated middleware to include booking.
- Updated booking routes to include middleware.
To enhance app restrictions and functionalities especially for booking management.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1711083876985869)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-78)
N/A
N/A
> Backend - Create API for managing bookings of a guest

- backend/app/Enums/BookingStatus.php
- backend/app/Http/Controllers/Api/V1/BookingController.php
- backend/app/Http/Middleware/CheckOwnership.php
- backend/app/Http/Middleware/CheckUserRole.php
- backend/app/Models/Admin.php
- backend/app/Models/Booking.php
- backend/app/Models/Listing.php
- backend/app/Models/User.php
- backend/database/migrations/2024_03_04_071150_create_bookings_table.php
- backend/routes/api.php
- Added APIs for managing the bookings of guests.
- Updated bookings table to include a new column named "host_deleted".
- Updated booking status enum.
- Updated status codes.
To enhance listing/booking management on the host side.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1711436117856119)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-99)
N/A
N/A
> Backend - Create API for managing bookings of a guest (host)

- frontend/src/app/(guest)/experiences/page.tsx
- frontend/src/app/components/accommodation/AccommodationTypeItem.tsx
- frontend/src/app/components/experience/ExperienceTypeItem.tsx
- frontend/src/app/components/experience/ExperienceTypes.tsx
- frontend/src/app/components/listings/AddNewListingButton.tsx
- frontend/src/app/components/listings/ListingHeader.tsx
- frontend/src/app/components/listings/ListingItem.tsx
- frontend/src/app/components/listings/ListingSearchBar.tsx
- frontend/src/app/layout.tsx
- frontend/src/app/utils/helpers/experience/request.ts
- add functionality to filter and search experiences
- it would be easier for guest to find the experience they want
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1711524087559119
- Task Link: https://framgiaph.backlog.com/view/SBNB-104
***
***
***
N/A
N/A
> add search and filter experiences

- frontend/src/app/components/calendar/AvailabilityCalendar.tsx
- frontend/src/app/components/calendar/AvailabilitySidebar.tsx
- frontend/src/app/components/calendar/Calendar.tsx
- frontend/src/app/components/calendar/CalendarDateButton.tsx
- frontend/src/app/components/calendar/ListingsDropdown.tsx
- frontend/src/app/components/listings/ListingHeader.tsx
- frontend/src/app/components/listings/ListingSearchBar.tsx
- frontend/src/app/interfaces/AvailabilityCalendarProps.ts
- frontend/src/app/interfaces/AvailabilitySidebarProps.ts
- frontend/src/app/interfaces/CalendarDateButtonProps.ts
- frontend/src/app/interfaces/CalendarProps.ts
- frontend/src/app/interfaces/ListingDropdownProps.ts
- frontend/src/app/interfaces/ListingsProps.tsx
- frontend/src/app/interfaces/types.ts
- frontend/src/app/layout.tsx
- frontend/src/app/utils/date.ts
- Show guest name on reserved dates
- Host would know if a guest has booked the listing for a specific date
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1712034580246619
- Task Link: https://framgiaph.backlog.com/view/SBNB-115
***
N/A
N/A
> update calendar listing availability

- frontend/src/app/(guest)/experiences/[id]/page.tsx
- frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
- frontend/src/app/(host)/listings/experiences/[id]/page.tsx
- frontend/src/app/components/StatusChip.tsx
- frontend/src/app/components/booking/AccommodationBookingConfirm.tsx
- frontend/src/app/components/booking/ExperienceBookingConfirm.tsx
- frontend/src/app/components/home/host/BookingActions.tsx
- frontend/src/app/components/home/host/ListingBookingsTable.tsx
- frontend/src/app/components/home/host/PendingListModal.tsx
- frontend/src/app/interfaces/types.ts
- frontend/src/app/utils/helpers/accommodation/request.ts
- frontend/src/app/utils/helpers/experience/request.ts
Remove types in types.ts that have similar attributes and make sure to refactor all files that uses said type.
To allow codebase to have easier maintainability and readability
- Slack Link: 
- Task Link: https://framgiaph.backlog.com/view/SBNB-112
N/A
N/A
N/A
> Remove duplicate types

- backend/app/Models/Review.php
- frontend/src/app/components/review/ReviewHeader.tsx
- frontend/src/app/components/review/ReviewSection.tsx
- frontend/src/app/utils/helpers/review/request.ts
Modified the fetch function for the rating counts of the overall rating.
To fix UI bug for review header
- Slack Link:
- Task Link: https://framgiaph.backlog.com/view/SBNB-139
N/A
N/A
N/A
> Fix review header

- frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
- frontend/src/app/(guest)/history/BookingHistoryData.tsx
- frontend/src/app/components/BookingStatus.tsx
- frontend/src/app/components/navbar/Navbar.tsx
- frontend/src/app/components/navbar/NavbarDropdown.tsx
- frontend/src/app/components/navbar/NavbarLinks.tsx
- Change badge component in history table
- Remove history link in public navigation
- The history table would be uniform with its host table counterpart
- Unlogged-in user would not be able to access the history page 
Slack Link: 
- https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1712130854468989
Task Link:
- https://framgiaph.backlog.com/view/SBNB-130
- https://framgiaph.backlog.com/view/SBNB-131
***
***
N/A
N/A
> update history page

- frontend/src/app/(auth)/admin/login/AdminLoginForm.tsx
- frontend/src/app/components/home/host/ListingBookingsTable.tsx
- frontend/src/app/page.tsx
- frontend/src/app/utils/helpers/adminHelper.ts
- frontend/src/middleware.ts
- Admin log in
- More middleware protection (calendar, history, and admin routes protection added)
- Fixed UI error in hosting home where chevron down icon is truncated.
- Allow admin to login
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1712225609943959
- Task Link: https://framgiaph.backlog.com/view/SBNB-141
Include screenshots to visually demonstrate the changes made by this pull request.
_Admin account logged in_
N/A
N/A
> Admin login integration

- frontend/src/app/(host)/calendar/page.tsx
- frontend/src/app/components/calendar/AvailabilityCalendar.tsx
- frontend/src/app/components/calendar/AvailabilitySidebar.tsx
- Add mobile responsiveness to calendar page
- The page would be responsive to any browser size
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1712825554765799
- Task Link: https://framgiaph.backlog.com/view/SBNB-147
N/A
N/A
> make calendar page mobile responsive

- frontend/src/app/components/admin/ReportDetailsModal.tsx
- Updated ui for the admin report view modal
To make it easier for the admin to see information
Why are these changes necessary?
- Slack Link:
- Task Link: https://framgiaph.backlog.com/view/SBNB-162
N/A
N/A
N/A
> added some fixes to the ui

- backend/app/Enums/UserStatus.php
- backend/app/Http/Controllers/Api/V1/AdminController.php
- backend/app/Http/Requests/V1/UserSortRequest.php
- backend/app/Models/Admin.php
- Added sort, filter, and search functionalities for user management.
- Updated UserStatus enum to include getConstants function.
To enhance app functionality and user experience by enabling admin to sort, filter, and search users.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713147372008779)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-160)
N/A
N/A
> Backend - Add filter, sort, and search for user management

- frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
- frontend/src/app/(guest)/history/BookingHistoryData.tsx
- frontend/src/app/components/home/host/FiltersSection.tsx
- Add mobile responsiveness to guest history page
- The page would be responsive to any browser size.
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713152700336419
- Task Link: https://framgiaph.backlog.com/view/SBNB-150
N/A
N/A
> add mobile responsiveness to guest history page

- .gitignore
- backend/.gitignore
- backend/config/analytics.php
- frontend/src/app/(auth)/role-selection/page.tsx
- frontend/src/app/(auth)/signup/SignUpForm.tsx
- frontend/src/app/components/RadioCard.tsx
- frontend/src/app/components/RoleSelectForm.tsx
- frontend/src/app/utils/helpers/adminHelper.ts
-Added mobile responsiveness for sign up page
-Added git ignore for analytics
-Allows users to view the page properly on mobile
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713162280860059
- Task Link: https://framgiaph.backlog.com/view/SBNB-157
_Sign up page on mobile_
N/A
N/A
> Mobile responsiveness for Sign Up page

- frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
- frontend/src/app/(guest)/history/BookingHistoryData.tsx
- frontend/src/app/components/home/host/FiltersSection.tsx
- frontend/src/app/components/home/host/HostDashboard.tsx
- frontend/src/app/components/home/host/ListingBookingsTable.tsx
- frontend/src/app/components/home/host/PendingCardsSlicer.tsx
- frontend/src/app/components/home/host/PendingListModal.tsx
- frontend/src/app/components/home/host/PendingListingCard.tsx
- Add mobile responsiveness to host home page
- The page would be responsive to any browser size.
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713166446102679
- Task Link: https://framgiaph.backlog.com/view/SBNB-163
N/A
N/A
> make host home page mobile responsive

- frontend/src/app/(auth)/login/LinkSuccessModal.tsx
- frontend/src/app/(auth)/login/ResetPasswordModal.tsx
- frontend/src/app/(auth)/reset-password/ResetSuccessModal.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/edit/ImageCollectionUpdate.tsx
- frontend/src/app/(host)/listings/accommodations/new/ImageCollection.tsx
- frontend/src/app/(host)/listings/accommodations/new/NewListingForm.tsx
- frontend/src/app/components/ApprovalModal.tsx
- frontend/src/app/components/DeleteModal.tsx
- frontend/src/app/components/ReportModal.tsx
- frontend/src/app/components/RoleSelectModal.tsx
- frontend/src/app/components/accommodation/Counter.tsx
- frontend/src/app/components/admin/ActionConfirmModal.tsx
- frontend/src/app/components/admin/AdminCard.tsx
- frontend/src/app/components/admin/UserAdminCard.tsx
- frontend/src/app/components/admin/UserGuestCard.tsx
- frontend/src/app/components/admin/UserHostCard.tsx
- frontend/src/app/components/booking/ThankYouModal.tsx
- frontend/src/app/components/experience/ExperienceApprovalModal.tsx
- frontend/src/app/components/home/host/PendingListModal.tsx
- frontend/src/app/components/review/AddReviewModal.tsx
- frontend/src/app/components/review/ReviewSuccessModal.tsx
- frontend/src/app/components/review/ShowReviewModal.tsx
Made it mobile responsive
To make it mobile responsive
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713168459205129
- Task Link: https://framgiaph.backlog.com/view/SBNB-151
N/A
N/A
> Mobile - Implement mobile responsive add/edit accommodation page

- frontend/src/app/(admin)/reports/AdminReportComponent.tsx
- frontend/src/app/components/admin/ReportCard.tsx
- frontend/src/app/components/admin/ReportDetailsModal.tsx
- frontend/src/app/components/admin/ReportTabStatus.tsx
- frontend/src/app/components/admin/UserGrid.tsx
Made a mobile responsive page for admin report management page.
To make the page mobile responsive.
- Slack Link:
- Task Link: https://framgiaph.backlog.com/view/SBNB-165
N/A
N/A
> Mobile - Implement admin reports management page

- frontend/src/app/(admin)/approvals/ListingsGrid.tsx
- frontend/src/app/(admin)/approvals/accommodation/[id]/page.tsx
- frontend/src/app/(admin)/approvals/experience/[id]/page.tsx
- frontend/src/app/(admin)/approvals/page.tsx
- frontend/src/app/(admin)/reports/AdminReportComponent.tsx
- frontend/src/app/(admin)/users/UserComponent.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
- frontend/src/app/components/admin/AdminApprover.tsx
Made the page mobile responsive.
To make the admin listings approval page mobile responsive
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713259686345699
- Task Link: https://framgiaph.backlog.com/view/SBNB-167
Include screenshots to visually demonstrate the changes made by this pull request.
N/A
N/A
> Mobile - Implement mobile responsive admin listings approval

- backend/app/Http/Controllers/Api/V1/AuthController.php
- backend/app/Models/Admin.php
- backend/app/Models/User.php
- backend/app/Traits/ResponseHandlingTrait.php
- frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
- frontend/src/app/(guest)/history/BookingHistoryData.tsx
- frontend/src/app/utils/helpers/userHelper.ts
- Check user status upon login.
- Banned user would not be able to login.
- Slack Link: https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713319571890059
- Task Link: https://framgiaph.backlog.com/view/SBNB-169
***
***
N/A
Please check/modify login methods and endpoint calls in client.
> check user status upon login

- frontend/src/app/(guest)/accommodations/[id]/page.tsx
- frontend/src/app/(guest)/experiences/[id]/page.tsx
- frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
- frontend/src/app/(host)/listings/experiences/[id]/page.tsx
- frontend/src/app/components/accommodation/AmenitySection.tsx
- frontend/src/app/components/accommodation/ListingHeader.tsx
- frontend/src/app/components/experience/ExperienceHeader.tsx
- frontend/src/app/components/review/ReviewComponent.tsx
- frontend/src/app/components/review/ReviewHeader.tsx
- Added mobile responsiveness to accommodation details page.
To enhance the user experience by allowing users to view app on mobile sizes.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713320406561469)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-148)
N/A
N/A
> Mobile - Implement mobile responsive accommodation details page

- backend/app/Http/Controllers/Api/V1/AdminController.php
- backend/app/Http/Controllers/Api/V1/BookingController.php
- backend/app/Http/Controllers/Api/V1/ListingController.php
- backend/app/Http/Controllers/Api/V1/SessionController.php
- backend/app/Http/Controllers/Api/V1/UserController.php
- backend/app/Models/Admin.php
- backend/app/Traits/ResponseHandlingTrait.php
- Updated response handling trait and applied to controllers.
- Refactored search query for users (admin side).
- Removed unused SessionController.
To clean up the code, ensuring better readability.
- [Slack Link](https://sun-philippine.slack.com/archives/C06JZLS2W5S/p1713337012721489)
- [Task Link](https://framgiaph.backlog.com/view/SBNB-173)
N/A
N/A
N/A
> Backend - Apply response trait and refactor code on searching users

- frontend/src/app/(admin)/reports/AdminReportComponent.tsx
- frontend/src/app/(admin)/users/UserComponent.tsx
- frontend/src/app/components/accommodation/ListingHeader.tsx
- frontend/src/app/components/admin/BanConfirmModal.tsx
- frontend/src/app/components/experience/ExperienceHeader.tsx
To allow it to refresh
So that it refreshes if there's an update
- Slack Link:
- Task Link: https://framgiaph.backlog.com/view/SBNB-174
N/A
N/A
N/A
> Report and User Ban does not refresh on update.
